service:
  name: vntg

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-2
  stage: dev
  environment:
    SOMETHING: ${file(./env.json):SOMETHING}
    COCKROACHDB_PW: ${file(./env.json):COCKROACHDB_PW}
    COCKROACHDB_HOST: ${file(./env.json):COCKROACHDB_HOST}
    SECRET_KEY: ${file(./env.json):SECRET_KEY}

functions:
  api:
    handler: src/api.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          path: /{any+}
          method: ANY
          cors: true
