service:
  name: vntg

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-2
  stage: dev

functions:
  api:
    handler: src/api.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          path: /{any+}
          method: ANY
